#ifndef HITABLE
#define HITABLE
#include "Sphere.compute"
#include "Plane.compute"
#include "Mesh.compute"
#include "SphereWithTexture.compute"
#include "PointLight.compute"
#include "DirectionalLight.compute"
//nothing
//Sphere SphereWithTexture Plane Mesh PointLight DirectionalLight类继承hitable
//hitable类的派生需要实现接口
//void Hit(Ray ray, inout RayHit bestHit)
//static void Init()
//float GetHitTime(Ray ray)
#endif